import type { Jobsite } from "./types";

/** Demo multi-family jobsite — reports, permit messages, and inspections already wired. */
export function createDemoJobsite(): Jobsite {
  const now = Date.now();
  const hours = (h: number) => new Date(now - h * 3600_000).toISOString();
  const daysAhead = (d: number) => {
    const dt = new Date(now + d * 86400_000);
    const y = dt.getFullYear();
    const m = String(dt.getMonth() + 1).padStart(2, "0");
    const day = String(dt.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  };

  return {
    id: "js_sample_demo",
    name: "Sample multi-family board — Building B",
    location: "United States (demo project)",
    cityState: undefined,
    permitNumber: "BP-2026-44108 (demo)",
    permittingOffice: "Local building department (demo)",
    country: "US",
    stateCode: undefined,
    isDemo: true,
    industry: "multi_family",
    projectStartDate: daysAhead(-30),
    materialsBudget: 1250000,
    captainName: "M. Reyes (site superintendent)",
    notes: "Sample US multi-family board. Wipe and create your project anytime.",
    updatedAt: new Date().toISOString(),
    reports: [
      {
        id: "fr_swq_p0",
        title: "Storm drain inlet blocked on south parking lot",
        body: "The stormwater quality inlet (the drain that filters runoff before it leaves the site) is full of silt after overnight rain. Standing water on the access road. City inspector is due tomorrow — need a vacuum truck or the walk-through may fail.",
        priority: "P0",
        urgency: "immediate",
        category: "permit",
        authorRole: "field",
        authorName: "M. Reyes (site superintendent)",
        status: "open",
        createdAt: hours(2),
        sendToAuthority: true,
        relatedMessageId: "msg_1",
        relatedInspectionId: "insp_swq",
      },
      {
        id: "fr_safety_p0",
        title: "Near-miss: loose scaffold plank on level 3",
        body: "A plank shifted under load on the west side, level 3. No injury. Crew stopped work in that bay. Need safety lead to mark this seen before restart.",
        priority: "P0",
        urgency: "immediate",
        category: "safety",
        authorRole: "field",
        authorName: "J. Okonkwo (safety)",
        status: "open",
        createdAt: hours(5),
        sendToAuthority: false,
      },
      {
        id: "fr_inspect_p1",
        title: "Rough-in work not ready for Thursday inspection",
        body: "Mechanical, electrical, and plumbing rough-in (pipes, wires, and ducts before walls close) on floors 4–5 is not ready for Thursday’s city slot. Office needs a decision: cancel the inspection or rebook (about +5 days).",
        priority: "P1",
        urgency: "today",
        category: "inspection",
        authorRole: "field",
        authorName: "A. Chen (general contractor)",
        status: "open",
        createdAt: hours(8),
        sendToAuthority: true,
        relatedMessageId: "msg_3",
        relatedInspectionId: "insp_roughin",
      },
      {
        id: "fr_material_p1",
        title: "Curtain-wall gaskets short by 12 pieces",
        body: "Supplier shorted the shipment. Install on bays 7–8 is blocked. Purchase-order change is waiting on the owner’s representative.",
        priority: "P1",
        urgency: "today",
        category: "materials",
        authorRole: "field",
        authorName: "T. Brooks (project manager)",
        status: "seen",
        createdAt: hours(14),
        seenAt: hours(10),
        seenBy: "Office desk",
        sendToAuthority: false,
      },
      {
        id: "fr_schedule_p2",
        title: "Crane lifts paused for wind",
        body: "Lifts paused 10:00 AM–2:00 PM for wind. Sequence reshuffled; no full stop yet.",
        priority: "P2",
        urgency: "today",
        category: "weather",
        authorRole: "field",
        authorName: "M. Reyes (site superintendent)",
        status: "open",
        createdAt: hours(3),
        sendToAuthority: false,
      },
      {
        id: "fr_fyi_p3",
        title: "Owner walk-through Friday 9:00 AM",
        body: "Owner and architect will walk Building B floors 1–3. Keep corridors clear; sample boards on floor 2.",
        priority: "P3",
        urgency: "this_week",
        category: "other",
        authorRole: "office",
        authorName: "Office desk",
        status: "open",
        createdAt: hours(20),
        sendToAuthority: false,
      },
    ],
    messages: [
      {
        id: "msg_1",
        direction: "field_to_authority",
        subject:
          "Active field report: Storm drain inlet blocked on south parking lot",
        body: "The stormwater quality inlet is full of silt after overnight rain. Standing water on the access road. City inspector is due tomorrow — need a vacuum truck or the walk-through may fail.\n\n— Auto-wired from active field reporting to the permit office",
        authorName: "M. Reyes (site superintendent)",
        authorRole: "field",
        status: "sent",
        createdAt: hours(1.5),
        relatedReportId: "fr_swq_p0",
        relatedInspectionId: "insp_swq",
        wiredFrom: "report",
      },
      {
        id: "msg_2",
        direction: "authority_to_field",
        subject: "Re: Storm drain — clear before inspector arrival",
        body: "Acknowledged. If the inlet is cleared and photo documentation is uploaded before the inspector arrives, the walk can proceed. Otherwise we will note a correction item.",
        authorName: "K. Patel (Development Services, demo)",
        authorRole: "authority",
        status: "read",
        createdAt: hours(0.5),
        relatedReportId: "fr_swq_p0",
        relatedInspectionId: "insp_swq",
        wiredFrom: "manual",
      },
      {
        id: "msg_3",
        direction: "office_to_authority",
        subject:
          "Inspection request: Rough-in (plumbing, electrical, and HVAC)",
        body: "Please schedule: Rough-in (plumbing, electrical, and HVAC) (MEP rough-in).\nArea: Building B, floors 4–5\nPreferred date: move from Thursday\n\nFloors 4–5 will not be open Thursday. Please advise next available morning window next week.\n\n— Wired inspection scheduling → permit office",
        authorName: "A. Chen (general contractor)",
        authorRole: "office",
        status: "sent",
        createdAt: hours(6),
        relatedInspectionId: "insp_roughin",
        relatedReportId: "fr_inspect_p1",
        wiredFrom: "inspection",
      },
    ],
    inspections: [
      {
        id: "insp_swq",
        typeLabel: "Stormwater / site drainage walk",
        typeCode: "SWQ walk",
        scheduledDate: daysAhead(1),
        timeWindow: "7:00 AM – 11:00 AM",
        buildingArea: "South parking lot & access road",
        status: "scheduled",
        requestedBy: "M. Reyes (site superintendent)",
        notes:
          "SWQ means stormwater quality — the drain filters that protect runoff leaving the site. Inlet must be clear before the walk. Linked to field report fr_swq_p0.",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(48),
        updatedAt: hours(12),
        relatedReportId: "fr_swq_p0",
        relatedMessageId: "msg_1",
      },
      {
        id: "insp_roughin",
        typeLabel: "Rough-in (plumbing, electrical, and HVAC)",
        typeCode: "MEP rough-in",
        scheduledDate: daysAhead(2),
        timeWindow: "8:00 AM – 12:00 PM",
        buildingArea: "Building B, floors 4–5",
        status: "requested",
        requestedBy: "A. Chen (general contractor)",
        notes:
          "MEP means mechanical, electrical, and plumbing. “Rough-in” is the inspection before walls and ceilings close over the pipes and wires. Currently not ready — reschedule likely.",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(30),
        updatedAt: hours(8),
        relatedReportId: "fr_inspect_p1",
        relatedMessageId: "msg_3",
      },
      {
        id: "insp_frame",
        typeLabel: "Framing inspection",
        scheduledDate: daysAhead(5),
        timeWindow: "1:00 PM – 4:00 PM",
        buildingArea: "Building B, floor 2",
        status: "scheduled",
        requestedBy: "Office desk",
        notes: "Structure open for review. Keep temporary bracing in place.",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(72),
        updatedAt: hours(24),
        relatedMessageId: undefined,
      },
      {
        id: "insp_foundation",
        typeLabel: "Foundation / slab (completed earlier)",
        scheduledDate: daysAhead(-14),
        timeWindow: "Morning window",
        buildingArea: "Building B foundation",
        status: "passed",
        requestedBy: "T. Brooks (project manager)",
        notes: "Passed. Card retained for records (demo).",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(400),
        updatedAt: hours(336),
      },
    ],
    contacts: [
      {
        id: "ct_mech",
        company: "Hill Country Mechanical",
        contactName: "Sam Ortiz",
        division: "mechanical",
        role: "subcontractor",
        phone: "(512) 555-0142",
        email: "sam@hcm-demo.example",
        scope: "HVAC rough-in and equipment set — Building B floors 4–5",
        inventoryNotes: "VAV boxes on site (12). Condenser pads short 2 units — PO open.",
        conditionNotes: "Floors 4–5 not ready for city rough-in Thursday.",
        leadTime: "Equipment: 5 days for shorted pads",
        active: true,
        createdAt: hours(72),
        updatedAt: hours(8),
      },
      {
        id: "ct_elec",
        company: "Lone Star Electric Co.",
        contactName: "Priya Nair",
        division: "electrical",
        role: "subcontractor",
        phone: "(512) 555-0198",
        scope: "Electrical rough-in Building B",
        inventoryNotes: "Panels staged in laydown. Homeline breakers complete.",
        conditionNotes: "Waiting on mechanical clearances on floor 5.",
        leadTime: "On site daily",
        active: true,
        createdAt: hours(60),
        updatedAt: hours(10),
      },
      {
        id: "ct_plumb",
        company: "Blue Line Plumbing",
        contactName: "Chris Webb",
        division: "plumbing",
        role: "subcontractor",
        phone: "(512) 555-0110",
        scope: "Plumbing rough-in floors 4–5",
        inventoryNotes: "Copper and PEX on site. Floor drains short 3 pcs.",
        conditionNotes: "Same readiness hold as MEP package.",
        active: true,
        createdAt: hours(55),
        updatedAt: hours(12),
      },
      {
        id: "ct_glaze",
        company: "Gulf Glass Systems",
        contactName: "Elena Vargas",
        division: "glazing",
        role: "vendor",
        phone: "(512) 555-0177",
        scope: "Curtain-wall gaskets and glass units bays 7–8",
        inventoryNotes: "Short 12 gaskets — change order with owner rep.",
        conditionNotes: "Install blocked on bays 7–8 until gaskets arrive.",
        leadTime: "Gaskets: 7–10 days after PO release",
        active: true,
        createdAt: hours(40),
        updatedAt: hours(14),
      },
      {
        id: "ct_swq",
        company: "Capitol Site Services",
        contactName: "Dispatch",
        division: "sitework",
        role: "vendor",
        phone: "(512) 555-0101",
        scope: "Vacuum truck / SWQ inlet cleanout",
        inventoryNotes: "Truck available tomorrow AM if released by 6pm.",
        conditionNotes: "South lot inlet silted — city SWQ walk tomorrow.",
        leadTime: "Same-day if booked before 6pm",
        active: true,
        createdAt: hours(20),
        updatedAt: hours(2),
      },
    ],
    schedule: [
      {
        id: "sch_found",
        title: "Foundation / slab (complete)",
        division: "concrete",
        startDate: daysAhead(-21),
        endDate: daysAhead(-14),
        status: "done",
        progress: 100,
        notes: "Passed inspection — demo history",
        createdAt: hours(500),
        updatedAt: hours(336),
      },
      {
        id: "sch_frame",
        title: "Framing — Building B floor 2",
        division: "carpentry",
        startDate: daysAhead(-2),
        endDate: daysAhead(5),
        status: "in_progress",
        progress: 55,
        contactId: undefined,
        createdAt: hours(100),
        updatedAt: hours(24),
      },
      {
        id: "sch_mep",
        title: "MEP rough-in floors 4–5",
        division: "mechanical",
        startDate: daysAhead(-5),
        endDate: daysAhead(4),
        status: "blocked",
        progress: 40,
        contactId: "ct_mech",
        relatedInspectionId: "insp_roughin",
        relatedReportId: "fr_inspect_p1",
        notes: "Not ready for Thursday city slot",
        createdAt: hours(90),
        updatedAt: hours(8),
      },
      {
        id: "sch_cw",
        title: "Curtain wall bays 7–8",
        division: "glazing",
        startDate: daysAhead(0),
        endDate: daysAhead(10),
        status: "blocked",
        progress: 15,
        contactId: "ct_glaze",
        relatedReportId: "fr_material_p1",
        notes: "Gasket short",
        createdAt: hours(48),
        updatedAt: hours(14),
      },
      {
        id: "sch_swq",
        title: "SWQ inlet cleanout",
        division: "sitework",
        startDate: daysAhead(0),
        endDate: daysAhead(1),
        status: "planned",
        progress: 0,
        contactId: "ct_swq",
        relatedInspectionId: "insp_swq",
        relatedReportId: "fr_swq_p0",
        milestone: false,
        createdAt: hours(10),
        updatedAt: hours(2),
      },
      {
        id: "sch_owner",
        title: "Owner walk-through",
        division: "general",
        startDate: daysAhead(3),
        endDate: daysAhead(3),
        status: "planned",
        progress: 0,
        milestone: true,
        notes: "Floors 1–3 corridors clear",
        createdAt: hours(20),
        updatedAt: hours(20),
      },
    ],
    materials: [
      {
        id: "mat_gaskets",
        name: "Curtain-wall gaskets",
        division: "glazing",
        unit: "ea",
        qtyRequired: 48,
        qtyOnHand: 36,
        unitCost: 28,
        quotedUnitCost: 31,
        status: "partial",
        vendorContactId: "ct_glaze",
        scheduleTaskId: "sch_cw",
        specNote: "Contract Section 08 44 00 — manufacturer approved equal only",
        poNote: "PO-4412 short 12 pcs",
        createdAt: hours(40),
        updatedAt: hours(14),
      },
      {
        id: "mat_vav",
        name: "VAV boxes (floors 4–5)",
        division: "mechanical",
        unit: "ea",
        qtyRequired: 14,
        qtyOnHand: 12,
        unitCost: 1850,
        status: "partial",
        vendorContactId: "ct_mech",
        scheduleTaskId: "sch_mep",
        specNote: "Mechanical schedule M-401",
        createdAt: hours(50),
        updatedAt: hours(8),
      },
      {
        id: "mat_copper",
        name: "Copper / PEX rough package",
        division: "plumbing",
        unit: "ls",
        qtyRequired: 1,
        qtyOnHand: 1,
        unitCost: 18500,
        status: "on_site",
        vendorContactId: "ct_plumb",
        scheduleTaskId: "sch_mep",
        specNote: "Division 22 — no PE-RT substitute without RFI",
        createdAt: hours(55),
        updatedAt: hours(12),
      },
      {
        id: "mat_swq",
        name: "Vacuum truck (SWQ cleanout)",
        division: "sitework",
        unit: "day",
        qtyRequired: 1,
        qtyOnHand: 0,
        unitCost: 2400,
        status: "needed",
        vendorContactId: "ct_swq",
        scheduleTaskId: "sch_swq",
        specNote: "Allowance in general conditions — book before inspector",
        createdAt: hours(5),
        updatedAt: hours(2),
      },
    ],
  };
}
