import type {
  FieldComm,
  FieldCommsLog,
  JobsiteProject,
  ProjectIdentity,
} from "./types";
import { uid } from "@/lib/utils";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAhead = (d: number) => {
  const dt = new Date(now + d * 86400_000);
  const y = dt.getFullYear();
  const m = String(dt.getMonth() + 1).padStart(2, "0");
  const day = String(dt.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
};

type SeedRow = {
  h: number;
  kind: string;
  phase: string;
  division: string;
  scopes?: string[];
  fromRole: string;
  toRoles: string[];
  fromName: string;
  toNames: string[];
  text: string;
  contractId?: string;
  vendorId?: string;
  ackRequired?: boolean;
  acked?: boolean;
};

function buildFieldComms(projectId: string): FieldCommsLog {
  const people = {
    super: "M. Reyes (site superintendent)",
    foreman: "R. Diaz (general foreman)",
    safety: "J. Okonkwo (safety)",
    mep: "S. Patel (MEP lead)",
    civil: "L. Nguyen (civil)",
    facade: "K. Okada (facade)",
    office: "A. Chen (GC PM)",
    owner: "Owner’s rep (demo)",
    bd: "K. Patel (Development Services, demo)",
    inspector: "City inspector desk (demo)",
  };

  const rows: SeedRow[] = [
    {
      h: 96,
      kind: "handoff",
      phase: "mobilization",
      division: "00",
      fromRole: "owner",
      toRoles: ["super", "foreman"],
      fromName: people.owner,
      toNames: [people.super, people.foreman],
      text: "Day 0 handoff — Building B multi-family sample board. Stop-work authority is superintendent. No trade NTP until gates clear.",
      ackRequired: true,
      acked: true,
    },
    {
      h: 90,
      kind: "ack",
      phase: "mobilization",
      division: "00",
      fromRole: "super",
      toRoles: ["owner", "foreman"],
      fromName: people.super,
      toNames: [people.owner, people.foreman],
      text: "Ack. Stop-work on safety/env is mine. Foreman sets daily brief. No cover before inspection.",
      acked: true,
    },
    {
      h: 72,
      kind: "site_pack",
      phase: "walkdown",
      division: "01",
      fromRole: "office",
      toRoles: ["super", "foreman", "safety"],
      fromName: people.office,
      toNames: [people.super, people.foreman, people.safety],
      text: "Site pack v3 posted — SWPPP, traffic control, temp power, and sample AHJ contact sheet. Photo notes stay on device until export.",
      acked: true,
    },
    {
      h: 60,
      kind: "status_update",
      phase: "active_work",
      division: "03",
      scopes: ["03", "05"],
      fromRole: "civil",
      toRoles: ["super", "foreman"],
      fromName: people.civil,
      toNames: [people.super, people.foreman],
      text: "Pad grade Building B east bay complete. Standing water at NW catch — pump on standby if overnight rain hits.",
    },
    {
      h: 48,
      kind: "inspection_request",
      phase: "inspection",
      division: "03",
      fromRole: "super",
      toRoles: ["bd", "office"],
      fromName: people.super,
      toNames: [people.bd, people.office],
      text: "Request footing / rebar inspection Building B grid lines 3–6. Area ready by 07:30. Contact Reyes on site.",
      ackRequired: true,
      acked: true,
    },
    {
      h: 42,
      kind: "bd_lane",
      phase: "inspection",
      division: "00",
      fromRole: "bd",
      toRoles: ["super", "office"],
      fromName: people.bd,
      toNames: [people.super, people.office],
      text: "Demo AHJ reply: footing inspection window tomorrow AM if bay remains open and photos of rebar chairs attached to field report.",
      acked: true,
    },
    {
      h: 36,
      kind: "escalation",
      phase: "deficiency",
      division: "05",
      scopes: ["05", "26"],
      fromRole: "mep",
      toRoles: ["super", "foreman", "office"],
      fromName: people.mep,
      toNames: [people.super, people.foreman, people.office],
      text: "P0 hold — temp power panel B-2 missing GFCI protection on wet-side circuits. Life-safety. No energize until remedied.",
      ackRequired: true,
      acked: false,
    },
    {
      h: 30,
      kind: "status_update",
      phase: "active_work",
      division: "09",
      fromRole: "facade",
      toRoles: ["super", "foreman"],
      fromName: people.facade,
      toNames: [people.super, people.foreman],
      text: "Curtain wall mock-up south elevation set. Need sealant lot certs before continuous run.",
    },
    {
      h: 24,
      kind: "handoff",
      phase: "active_work",
      division: "00",
      fromRole: "foreman",
      toRoles: ["super", "safety"],
      fromName: people.foreman,
      toNames: [people.super, people.safety],
      text: "Night shift handoff: crane reserved 05:00–09:00 for panel set. Exclusion zone marked. Photo of signage in photo notes.",
      ackRequired: true,
      acked: true,
    },
    {
      h: 18,
      kind: "inspection_result",
      phase: "inspection",
      division: "03",
      fromRole: "inspector",
      toRoles: ["super", "office", "bd"],
      fromName: people.inspector,
      toNames: [people.super, people.office, people.bd],
      text: "Demo result: footing lines 3–4 passed. Lines 5–6 — chair height deficient at two locations. Correct and re-request.",
      acked: true,
    },
    {
      h: 14,
      kind: "status_update",
      phase: "resolution",
      division: "03",
      fromRole: "civil",
      toRoles: ["super", "foreman", "bd"],
      fromName: people.civil,
      toNames: [people.super, people.foreman, people.bd],
      text: "Chairs corrected on 5–6. Ready for re-look. Photos tagged to report FR footing deficiency.",
    },
    {
      h: 10,
      kind: "bd_lane",
      phase: "active_work",
      division: "00",
      fromRole: "office",
      toRoles: ["bd", "super"],
      fromName: people.office,
      toNames: [people.bd, people.super],
      text: "Packet prep: export will include open P0, field log, and any photo notes linked to reports. Not a city system of record.",
    },
    {
      h: 8,
      kind: "status_update",
      phase: "active_work",
      division: "22",
      scopes: ["22", "23"],
      fromRole: "mep",
      toRoles: ["super", "foreman"],
      fromName: people.mep,
      toNames: [people.super, people.foreman],
      text: "Rough plumbing B level 2 60%. Need slab pour freeze for wet walls until pressure test complete.",
    },
    {
      h: 6,
      kind: "escalation",
      phase: "deficiency",
      division: "01",
      fromRole: "safety",
      toRoles: ["super", "foreman", "owner"],
      fromName: people.safety,
      toNames: [people.super, people.foreman, people.owner],
      text: "P1 — fall protection incomplete on stair tower 2 landings. Barricade in place. Crew staged off until corrected.",
      ackRequired: true,
      acked: false,
    },
    {
      h: 4,
      kind: "status_update",
      phase: "active_work",
      division: "26",
      fromRole: "foreman",
      toRoles: ["super", "mep"],
      fromName: people.foreman,
      toNames: [people.super, people.mep],
      text: "GFCI kits staged at B-2. Electrician ETA 14:00. Will photo-document install before request to clear P0.",
    },
    {
      h: 2,
      kind: "status_update",
      phase: "active_work",
      division: "00",
      fromRole: "super",
      toRoles: ["office", "owner", "foreman"],
      fromName: people.super,
      toNames: [people.office, people.owner, people.foreman],
      text: "Daily brief: hold on wet-side energize; stair tower barricade; re-inspect footings 5–6 when open. Role lens on phone must match who files.",
      ackRequired: true,
      acked: false,
    },
  ];

  const messages: FieldComm[] = rows.map((r) => ({
    id: uid("cm"),
    projectId,
    kind: r.kind,
    phase: r.phase,
    division: r.division,
    scopes: r.scopes,
    fromRole: r.fromRole,
    toRoles: r.toRoles,
    fromName: r.fromName,
    toNames: r.toNames,
    text: r.text,
    contractId: r.contractId,
    vendorId: r.vendorId,
    ackRequired: r.ackRequired,
    acked: r.acked,
    createdAt: hours(r.h),
  }));

  return {
    version: 1,
    projectId,
    messages,
    generatedAt: new Date().toISOString(),
  };
}

/** Blank live board — full mobile setup starts here. */
export function createEmptyJobsite(
  identity?: Partial<ProjectIdentity>,
): JobsiteProject {
  const id = uid("js");
  const name = identity?.name?.trim() || "My jobsite";
  return {
    id,
    name,
    location: identity?.location?.trim() || "United States",
    cityState: identity?.cityState?.trim() || undefined,
    permitNumber: identity?.permitNumber?.trim() || "TBD",
    permittingOffice:
      identity?.permittingOffice?.trim() || "City / County Building Department",
    captainName: identity?.captainName?.trim() || "",
    isDemo: false,
    industry: identity?.industry?.trim() || "commercial",
    notes: identity?.notes?.trim() || "",
    stateCode: identity?.stateCode?.trim().toUpperCase().slice(0, 2) || undefined,
    projectStartDate: identity?.projectStartDate,
    materialsBudget: identity?.materialsBudget,
    country: "US",
    reports: [],
    messages: [],
    fieldComms: {
      version: 1,
      projectId: id,
      messages: [],
      generatedAt: new Date().toISOString(),
    },
    inspections: [],
    materials: [],
    schedule: [],
    contacts: [],
    photos: [],
    site: {
      version: 1,
      note: "Drop a pin on Map for this jobsite. Geometry stays on this device.",
    },
    updatedAt: new Date().toISOString(),
  };
}

export function applyProjectIdentity(
  project: JobsiteProject,
  identity: ProjectIdentity,
): JobsiteProject {
  return {
    ...project,
    name: identity.name.trim() || project.name,
    location: identity.location.trim() || project.location,
    cityState: identity.cityState?.trim() || undefined,
    permitNumber: identity.permitNumber.trim() || project.permitNumber,
    permittingOffice:
      identity.permittingOffice.trim() || project.permittingOffice,
    stateCode:
      identity.stateCode?.trim().toUpperCase().slice(0, 2) || undefined,
    captainName: identity.captainName?.trim() || "",
    notes: identity.notes?.trim() || "",
    industry: identity.industry?.trim() || project.industry,
    projectStartDate: identity.projectStartDate ?? project.projectStartDate,
    materialsBudget: identity.materialsBudget ?? project.materialsBudget,
    isDemo: false,
    country: "US",
    updatedAt: new Date().toISOString(),
  };
}

/** Demo multi-family jobsite — field-dense sample. */
export function createDemoJobsite(): JobsiteProject {
  const id = "js_sample_demo";
  return {
    id,
    name: "Sample multi-family board — Building B",
    location: "United States (demo project)",
    cityState: undefined,
    permitNumber: "BP-2026-44108 (demo)",
    permittingOffice: "Local building department (demo)",
    captainName: "M. Reyes, site superintendent",
    isDemo: true,
    industry: "multi_family",
    notes:
      "Sample board for field walkthrough. Demo permits are labeled — never treat as a live file. Start a blank jobsite from Setup when ready for real work.",
    stateCode: "TX",
    projectStartDate: daysAhead(-45),
    materialsBudget: 2_400_000,
    country: "US",
    reports: [
      {
        id: "fr_p0_power",
        title: "Temp power B-2 missing GFCI (wet side)",
        body: "Panel B-2 wet-side circuits lack GFCI. Stop energize until kits installed and photo-documented. Life-safety hold — superintendent owns clear.",
        priority: "P0",
        urgency: "immediate",
        category: "safety",
        authorRole: "field",
        authorName: "S. Patel (MEP lead)",
        status: "open",
        createdAt: hours(36),
        sendToAuthority: false,
        area: "Building B · temp power · panel B-2",
      },
      {
        id: "fr_p1_fall",
        title: "Stair tower 2 — incomplete fall protection",
        body: "Landings missing mid-rail sections. Barricade up; crews staged off tower until corrected. Photo note recommended for insurance pack.",
        priority: "P1",
        urgency: "today",
        category: "safety",
        authorRole: "field",
        authorName: "J. Okonkwo (safety)",
        status: "open",
        createdAt: hours(6),
        sendToAuthority: false,
        area: "Stair tower 2",
      },
      {
        id: "fr_footing",
        title: "Footing re-inspect needed lines 5–6",
        body: "Inspector found chair height deficiency at two locations. Corrected chairs; re-request when bay open. Attach photos to this report from Board.",
        priority: "P1",
        urgency: "today",
        category: "inspection",
        authorRole: "field",
        authorName: "L. Nguyen (civil)",
        status: "seen",
        seenAt: hours(12),
        seenBy: "M. Reyes",
        createdAt: hours(18),
        sendToAuthority: true,
        area: "Building B · grid 5–6",
      },
      {
        id: "fr_sealant",
        title: "Curtain wall sealant lot certs pending",
        body: "Mock-up set south elevation. Continuous run blocked until lot certificates on file with office.",
        priority: "P2",
        urgency: "this_week",
        category: "materials",
        authorRole: "office",
        authorName: "A. Chen (GC PM)",
        status: "open",
        createdAt: hours(30),
        sendToAuthority: false,
        area: "South elevation",
      },
      {
        id: "fr_weather",
        title: "NW catch standing water watch",
        body: "Pad grade east bay complete. Pump staged if overnight rain. Not a stop-work — monitor only.",
        priority: "P3",
        urgency: "whenever",
        category: "weather",
        authorRole: "field",
        authorName: "L. Nguyen (civil)",
        status: "resolved",
        seenAt: hours(50),
        seenBy: "R. Diaz",
        createdAt: hours(60),
        sendToAuthority: false,
        area: "NW catch basin",
      },
    ],
    messages: [
      {
        id: "msg_bd_1",
        direction: "field_to_authority",
        subject: "Footing inspection request — Building B 3–6",
        body: "Area ready 07:30. Contact Reyes on site. Demo AHJ lane only.",
        authorName: "M. Reyes (site superintendent)",
        authorRole: "field",
        status: "replied",
        createdAt: hours(48),
        wiredFrom: "report",
        relatedReportId: "fr_footing",
      },
      {
        id: "msg_bd_2",
        direction: "authority_to_field",
        subject: "Re: Footing window + photo requirement",
        body: "Demo AHJ: tomorrow AM if bay open and rebar chair photos attached to field report.",
        authorName: "K. Patel (Development Services, demo)",
        authorRole: "authority",
        status: "read",
        createdAt: hours(42),
        wiredFrom: "manual",
      },
      {
        id: "msg_int_1",
        direction: "internal",
        subject: "Packet export reminder",
        body: "Before desk handoff, export pack with open P0, log, and photo notes. Device-local until then.",
        authorName: "A. Chen (GC PM)",
        authorRole: "office",
        status: "sent",
        createdAt: hours(10),
        wiredFrom: "manual",
      },
    ],
    fieldComms: buildFieldComms(id),
    inspections: [
      {
        id: "insp_foot",
        typeLabel: "Footing / rebar — Building B",
        scheduledDate: daysAhead(1),
        timeWindow: "07:30–10:00",
        buildingArea: "Grid lines 3–6",
        status: "ready_for_inspector",
        requestedBy: "M. Reyes",
        notes: "Re-look on 5–6 after chair correction. Photos recommended.",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(48),
        relatedReportId: "fr_footing",
      },
      {
        id: "insp_frame",
        typeLabel: "Framing rough — level 2",
        scheduledDate: daysAhead(5),
        timeWindow: "Afternoon",
        buildingArea: "Building B level 2",
        status: "requested",
        requestedBy: "R. Diaz",
        notes: "Hold until wet walls pressure-tested.",
        authorityOffice: "Local building department (demo)",
        createdAt: hours(20),
      },
    ],
    materials: [
      {
        id: "mat_gfci",
        name: "GFCI breaker kits (wet side)",
        qty: 12,
        unit: "ea",
        status: "on_site",
        note: "Staged at B-2 for P0 clear",
        division: "26",
      },
      {
        id: "mat_seal",
        name: "Structural sealant — approved lot",
        qty: 40,
        unit: "tube",
        status: "ordered",
        note: "Certs pending office",
        division: "07",
      },
      {
        id: "mat_rail",
        name: "Mid-rail sections stair tower 2",
        qty: 8,
        unit: "ea",
        status: "short",
        note: "P1 fall protection",
        division: "05",
      },
      {
        id: "mat_pump",
        name: "Trash pump 3\"",
        qty: 1,
        unit: "ea",
        status: "on_site",
        note: "NW catch standby",
        division: "01",
      },
    ],
    schedule: [
      {
        id: "sch_crane",
        name: "Panel set — south elevation",
        start: daysAhead(0),
        end: daysAhead(0),
        status: "on_track",
        owner: "Facade / crane",
        pct: 20,
      },
      {
        id: "sch_power",
        name: "Clear temp power P0",
        start: daysAhead(0),
        end: daysAhead(0),
        status: "blocked",
        owner: "MEP / super",
        pct: 40,
      },
      {
        id: "sch_foot",
        name: "Footing re-inspect 5–6",
        start: daysAhead(1),
        end: daysAhead(1),
        status: "at_risk",
        owner: "Civil",
        pct: 70,
      },
      {
        id: "sch_plumb",
        name: "Rough plumbing L2 complete",
        start: daysAhead(2),
        end: daysAhead(4),
        status: "on_track",
        owner: "MEP",
        pct: 60,
      },
    ],
    contacts: [
      {
        id: "ct_super",
        name: "M. Reyes",
        role: "Site superintendent",
        org: "GC — field",
        phone: "(555) 010-2201",
        lane: "field",
      },
      {
        id: "ct_fore",
        name: "R. Diaz",
        role: "General foreman",
        org: "GC — field",
        phone: "(555) 010-2202",
        lane: "field",
      },
      {
        id: "ct_pm",
        name: "A. Chen",
        role: "Project manager",
        org: "GC — office",
        email: "pm.demo@example.com",
        lane: "office",
      },
      {
        id: "ct_bd",
        name: "K. Patel",
        role: "Plans examiner (demo)",
        org: "Development Services (demo)",
        phone: "(555) 010-9900",
        lane: "authority",
      },
      {
        id: "ct_own",
        name: "Owner’s rep (demo)",
        role: "Owner representative",
        org: "Owner",
        lane: "owner",
      },
    ],
    photos: [],
    site: {
      version: 1,
      pin: { lat: 30.2672, lon: -97.7431, label: "Building B (demo pin)" },
      boundaryRing: [
        [-97.7438, 30.2678],
        [-97.7424, 30.2678],
        [-97.7424, 30.2666],
        [-97.7438, 30.2666],
        [-97.7438, 30.2678],
      ],
      note: "Demo pin near Austin metro — replace with your site on Map.",
    },
    updatedAt: new Date().toISOString(),
  };
}
