/**
 * OPSEC-safe portfolio baseline — ~50 US regions (no municipality names),
 * all construction industries, varied environmental conditions.
 * Synthetic field data only. Locality = demo metro by state — not real cities (geo OPSEC).
 */

import type { ConstructionIndustry } from "./types";
import type { EnvCondition, InterestTag, ProjectMeta } from "./project-types";

type Seed = Omit<ProjectMeta, "id"> & { slug: string };

const SEEDS: Seed[] = [
  // —— West / Pacific ——
  {
    slug: "ca-single-family-ionsfr",
    name: "Townhome Court",
    city: "Demo metro (CA)",
    stateCode: "CA",
    industry: "single_family",
    env: ["seismic", "coastal_flood", "urban_dense"],
    interests: ["envelope", "foundation_deep", "life_safety"],
    phase: "structure",
    lat: 36.8,
    lon: -119.4,
    permitOffice: "Local building department (demo)",
    captain: "A. Nguyen (superintendent)",
    blurb: "Stacked townhomes on soft soils — seismic + flood plain detailing.",
    materialsBudget: 4_200_000,
    startOffsetDays: -120,
  },
  {
    slug: "ca-multi-family-dtlamf",
    name: "Residences — Tower A",
    city: "Demo metro (CA)",
    stateCode: "CA",
    industry: "multi_family",
    env: ["seismic", "urban_dense", "wildfire_wui"],
    interests: ["high_rise", "life_safety", "crane_picks", "union_labor"],
    phase: "envelope",
    lat: 36.8,
    lon: -119.4,
    permitOffice: "Local building department (demo)",
    captain: "R. Alvarez (PM)",
    blurb: "Type I podium MF; curtain wall and life-safety phased floors.",
    materialsBudget: 48_000_000,
    startOffsetDays: -280,
  },
  {
    slug: "ca-healthcare-echlab",
    name: "Lab Fit-Out",
    city: "Demo metro (CA)",
    stateCode: "CA",
    industry: "healthcare",
    env: ["seismic", "coastal_flood"],
    interests: ["healthcare_icra", "occupied_site", "life_safety"],
    phase: "mep",
    lat: 36.8,
    lon: -119.4,
    permitOffice: "Local building department (demo)",
    captain: "K. Patel (site lead)",
    blurb: "Occupied lab TI — infection control and specialty gases.",
    materialsBudget: 9_500_000,
    startOffsetDays: -90,
  },
  {
    slug: "ca-education-olwing",
    name: "Elementary Wing",
    city: "Demo metro (CA)",
    stateCode: "CA",
    industry: "education",
    env: ["wildfire_wui", "expansive_soil"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "foundation",
    lat: 36.8,
    lon: -119.4,
    permitOffice: "Local building department (demo)",
    captain: "L. Brooks (GC)",
    blurb: "DSA-style phased school wing; summer occupancy target.",
    materialsBudget: 12_000_000,
    startOffsetDays: -45,
  },
  {
    slug: "wa-hospitality-thotel",
    name: "Boutique Hotel",
    city: "Demo metro (WA)",
    stateCode: "WA",
    industry: "hospitality",
    env: ["seismic", "coastal_flood", "cold_winter"],
    interests: ["hospitality_ffe", "envelope", "life_safety", "union_labor"],
    phase: "finish",
    lat: 47.4,
    lon: -120.5,
    permitOffice: "Local building department (demo)",
    captain: "M. Okonkwo (superintendent)",
    blurb: "Waterfront hospitality; FF&E and energy envelope punch.",
    materialsBudget: 22_000_000,
    startOffsetDays: -310,
  },
  {
    slug: "or-civil-ecivil",
    name: "Willamette Trail Connector",
    city: "Demo metro (OR)",
    stateCode: "OR",
    industry: "civil",
    env: ["wetland_swq", "seismic", "cold_winter"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 44,
    lon: -120.5,
    permitOffice: "Local building department (demo)",
    captain: "J. Hale (civil lead)",
    blurb: "Multi-use path + drainage; wetland SWQ BMPs critical.",
    materialsBudget: 6_800_000,
    startOffsetDays: -160,
  },
  {
    slug: "id-industrial-ehouse",
    name: "Treasure Valley Logistics Hub",
    city: "Demo metro (ID)",
    stateCode: "ID",
    industry: "industrial",
    env: ["freeze_thaw", "high_wind_plain"],
    interests: ["tilt_up", "logistics", "steel_structure"],
    phase: "structure",
    lat: 44.4,
    lon: -114.6,
    permitOffice: "Local building department (demo)",
    captain: "T. Vargas (PM)",
    blurb: "Tilt-up warehouse; freeze protection on slab pours.",
    materialsBudget: 18_500_000,
    startOffsetDays: -100,
  },
  {
    slug: "nv-industrial-ashell",
    name: "Truckee Meadows Data Hall Shell",
    city: "Demo metro (NV)",
    stateCode: "NV",
    industry: "industrial",
    env: ["desert_heat", "seismic", "high_altitude"],
    interests: ["steel_structure", "logistics", "net_zero"],
    phase: "envelope",
    lat: 39.3,
    lon: -116.6,
    permitOffice: "Local building department (demo)",
    captain: "S. Kim (superintendent)",
    blurb: "Steel shell + heavy power; high desert thermal swings.",
    materialsBudget: 35_000_000,
    startOffsetDays: -200,
  },

  // —— Southwest / Mountain ——
  {
    slug: "az-commercial-ailpad",
    name: "Desert Ridge Retail Pad B",
    city: "Demo metro (AZ)",
    stateCode: "AZ",
    industry: "commercial",
    env: ["desert_heat", "expansive_soil"],
    interests: ["envelope", "logistics", "night_work"],
    phase: "mep",
    lat: 34.3,
    lon: -111.7,
    permitOffice: "Local building department (demo)",
    captain: "D. Morales (GC)",
    blurb: "Pad retail under extreme heat — night pours and UV membrane.",
    materialsBudget: 5_400_000,
    startOffsetDays: -70,
  },
  {
    slug: "az-multi-family-garden",
    name: "Catalina Foothills Garden MF",
    city: "Demo metro (AZ)",
    stateCode: "AZ",
    industry: "multi_family",
    env: ["desert_heat", "wildfire_wui"],
    interests: ["life_safety", "stormwater", "envelope"],
    phase: "foundation",
    lat: 34.3,
    lon: -111.7,
    permitOffice: "Local building department (demo)",
    captain: "P. Ortiz (superintendent)",
    blurb: "Garden-style MF; WUI hardening and monsoon drainage.",
    materialsBudget: 14_200_000,
    startOffsetDays: -40,
  },
  {
    slug: "nm-healthcare-alwing",
    name: "Rio Grande Med Center Wing C",
    city: "Demo metro (NM)",
    stateCode: "NM",
    industry: "healthcare",
    env: ["high_altitude", "freeze_thaw", "expansive_soil"],
    interests: ["healthcare_icra", "life_safety", "public_funding"],
    phase: "structure",
    lat: 34.4,
    lon: -106.1,
    permitOffice: "Local building department (demo)",
    captain: "H. Singh (PM)",
    blurb: "Hospital addition; altitude curing and ICRA zones.",
    materialsBudget: 41_000_000,
    startOffsetDays: -190,
  },
  {
    slug: "co-hospitality-thotel",
    name: "Front Range Airport Hotel",
    city: "Demo metro (CO)",
    stateCode: "CO",
    industry: "hospitality",
    env: ["high_altitude", "freeze_thaw", "high_wind_plain"],
    interests: ["hospitality_ffe", "envelope", "crane_picks"],
    phase: "envelope",
    lat: 39,
    lon: -105.5,
    permitOffice: "Local building department (demo)",
    captain: "C. Berg (superintendent)",
    blurb: "High-altitude hospitality; wind and freeze envelope detailing.",
    materialsBudget: 28_000_000,
    startOffsetDays: -220,
  },
  {
    slug: "ut-commercial-etower",
    name: "Wasatch Commerce Tower",
    city: "Demo metro (UT)",
    stateCode: "UT",
    industry: "commercial",
    env: ["seismic", "freeze_thaw", "high_altitude"],
    interests: ["high_rise", "steel_structure", "life_safety"],
    phase: "structure",
    lat: 39.3,
    lon: -111.7,
    permitOffice: "Local building department (demo)",
    captain: "E. Jensen (PM)",
    blurb: "Steel commercial tower; seismic bracing package open.",
    materialsBudget: 62_000_000,
    startOffsetDays: -250,
  },
  {
    slug: "nv-renovation-vation",
    name: "Strip Corridor TI — Suite 400",
    city: "Demo metro (NV)",
    stateCode: "NV",
    industry: "renovation",
    env: ["desert_heat", "urban_dense"],
    interests: ["occupied_site", "night_work", "hospitality_ffe"],
    phase: "finish",
    lat: 39.3,
    lon: -116.6,
    permitOffice: "Local building department (demo)",
    captain: "N. Cho (TI lead)",
    blurb: "Occupied casino corridor TI; night work only.",
    materialsBudget: 3_100_000,
    startOffsetDays: -55,
  },

  // —— Texas / South Central ——
  {
    slug: "tx-civil-emyard",
    name: "Ship Channel Utility Yard",
    city: "Demo metro (TX)",
    stateCode: "TX",
    industry: "civil",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "expansive_soil"],
    interests: ["civil_utilities", "stormwater", "logistics"],
    phase: "structure",
    lat: 31.5,
    lon: -99.3,
    permitOffice: "Local building department (demo)",
    captain: "B. Carter (civil PM)",
    blurb: "Utility corridor; hurricane and expansive clay staging.",
    materialsBudget: 11_000_000,
    startOffsetDays: -130,
  },
  {
    slug: "tx-multi-family-idrise",
    name: "Mid-Rise MF",
    city: "Demo metro (TX)",
    stateCode: "TX",
    industry: "multi_family",
    env: ["tornado_alley", "expansive_soil", "humid_subtropical"],
    interests: ["life_safety", "steel_structure", "crane_picks"],
    phase: "mep",
    lat: 31.5,
    lon: -99.3,
    permitOffice: "Local building department (demo)",
    captain: "F. Ramirez (superintendent)",
    blurb: "Mid-rise MF; severe wind and clay foundation monitoring.",
    materialsBudget: 33_000_000,
    startOffsetDays: -175,
  },
  {
    slug: "tx-single-family-rgreen",
    name: "Barton Hills Net-Zero SFR",
    city: "Demo metro (TX)",
    stateCode: "TX",
    industry: "single_family",
    env: ["humid_subtropical", "expansive_soil", "wildfire_wui"],
    interests: ["net_zero", "envelope", "stormwater"],
    phase: "envelope",
    lat: 31.5,
    lon: -99.3,
    permitOffice: "Local building department (demo)",
    captain: "G. Wells (builder)",
    blurb: "Net-zero SFR; air sealing and rainwater management.",
    materialsBudget: 1_850_000,
    startOffsetDays: -80,
  },
  {
    slug: "tx-industrial-strial",
    name: "Alamo Logistics Crossdock",
    city: "Demo metro (TX)",
    stateCode: "TX",
    industry: "industrial",
    env: ["humid_subtropical", "expansive_soil", "high_wind_plain"],
    interests: ["tilt_up", "logistics", "steel_structure"],
    phase: "foundation",
    lat: 31.5,
    lon: -99.3,
    permitOffice: "Local building department (demo)",
    captain: "I. Soto (PM)",
    blurb: "Tilt-up crossdock; soil prep and dock levelers.",
    materialsBudget: 16_500_000,
    startOffsetDays: -35,
  },
  {
    slug: "ok-education-school",
    name: "Prairie View Middle School",
    city: "Demo metro (OK)",
    stateCode: "OK",
    industry: "education",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "structure",
    lat: 35.6,
    lon: -97.5,
    permitOffice: "Local building department (demo)",
    captain: "W. Price (GC)",
    blurb: "Safe-room school; tornado resistance package.",
    materialsBudget: 24_000_000,
    startOffsetDays: -150,
  },
  {
    slug: "la-hospitality-tality",
    name: "French Quarter Courtyard Inn",
    city: "Demo metro (LA)",
    stateCode: "LA",
    industry: "hospitality",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "wetland_swq"],
    interests: ["historic", "hospitality_ffe", "life_safety", "envelope"],
    phase: "finish",
    lat: 31,
    lon: -92,
    permitOffice: "Local building department (demo)",
    captain: "Y. Baptiste (superintendent)",
    blurb: "Historic hospitality; floodproofing and FF&E punch.",
    materialsBudget: 8_900_000,
    startOffsetDays: -260,
  },

  // —— Southeast ——
  {
    slug: "fl-multi-family-risemf",
    name: "Brickell Waterfront Residences",
    city: "Demo metro (FL)",
    stateCode: "FL",
    industry: "multi_family",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical"],
    interests: ["high_rise", "life_safety", "envelope", "crane_picks"],
    phase: "structure",
    lat: 28.1,
    lon: -81.7,
    permitOffice: "Local building department (demo)",
    captain: "L. Duarte (PM)",
    blurb: "Coastal high-rise MF; impact glazing and surge criteria.",
    materialsBudget: 95_000_000,
    startOffsetDays: -300,
  },
  {
    slug: "fl-civil-bridge",
    name: "Bay Causeway Utility Rehab",
    city: "Demo metro (FL)",
    stateCode: "FL",
    industry: "civil",
    env: ["coastal_hurricane", "coastal_flood", "wetland_swq"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "mep",
    lat: 28.1,
    lon: -81.7,
    permitOffice: "Local building department (demo)",
    captain: "R. Singh (civil)",
    blurb: "Causeway utilities; storm season work windows.",
    materialsBudget: 7_200_000,
    startOffsetDays: -95,
  },
  {
    slug: "ga-commercial-ercial",
    name: "Office Shell",
    city: "Demo metro (GA)",
    stateCode: "GA",
    industry: "commercial",
    env: ["humid_subtropical", "urban_dense"],
    interests: ["steel_structure", "life_safety", "union_labor"],
    phase: "envelope",
    lat: 32.7,
    lon: -83.2,
    permitOffice: "Local building department (demo)",
    captain: "K. Washington (superintendent)",
    blurb: "Urban office shell; fireproofing and curtain wall.",
    materialsBudget: 44_000_000,
    startOffsetDays: -210,
  },
  {
    slug: "sc-single-family-oastal",
    name: "Lowcountry Elevated SFR",
    city: "Demo metro (SC)",
    stateCode: "SC",
    industry: "single_family",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "wetland_swq"],
    interests: ["envelope", "stormwater", "foundation_deep"],
    phase: "foundation",
    lat: 33.9,
    lon: -80.9,
    permitOffice: "Local building department (demo)",
    captain: "A. Rivers (builder)",
    blurb: "Elevated SFR; flood vents and coastal wind straps.",
    materialsBudget: 1_450_000,
    startOffsetDays: -50,
  },
  {
    slug: "nc-healthcare-thcare",
    name: "Piedmont Outpatient Pavilion",
    city: "Demo metro (NC)",
    stateCode: "NC",
    industry: "healthcare",
    env: ["humid_subtropical", "expansive_soil"],
    interests: ["healthcare_icra", "life_safety", "public_funding"],
    phase: "mep",
    lat: 35.6,
    lon: -79.8,
    permitOffice: "Local building department (demo)",
    captain: "S. Grant (PM)",
    blurb: "Outpatient pavilion; medical gas and ICRA barriers.",
    materialsBudget: 29_000_000,
    startOffsetDays: -140,
  },
  {
    slug: "tn-hospitality-hhotel",
    name: "Music Row Boutique Hotel",
    city: "Demo metro (TN)",
    stateCode: "TN",
    industry: "hospitality",
    env: ["humid_subtropical", "tornado_alley"],
    interests: ["hospitality_ffe", "historic", "life_safety"],
    phase: "finish",
    lat: 35.9,
    lon: -86.4,
    permitOffice: "Local building department (demo)",
    captain: "J. Cole (superintendent)",
    blurb: "Adaptive hospitality; tornado shelter and FF&E.",
    materialsBudget: 15_500_000,
    startOffsetDays: -240,
  },
  {
    slug: "va-renovation-vation",
    name: "Shockoe Warehouse TI",
    city: "Demo metro (VA)",
    stateCode: "VA",
    industry: "renovation",
    env: ["humid_subtropical", "urban_dense"],
    interests: ["historic", "occupied_site", "envelope"],
    phase: "mep",
    lat: 37.5,
    lon: -78.9,
    permitOffice: "Local building department (demo)",
    captain: "M. Ellis (TI lead)",
    blurb: "Historic warehouse TI; selective demo and fire egress.",
    materialsBudget: 4_600_000,
    startOffsetDays: -65,
  },

  // —— Mid-Atlantic / Northeast ——
  {
    slug: "ny-commercial-ghrise",
    name: "Hudson Yards Block Infill",
    city: "Demo metro (NY)",
    stateCode: "NY",
    industry: "commercial",
    env: ["urban_dense", "coastal_flood", "cold_winter"],
    interests: ["high_rise", "steel_structure", "union_labor", "crane_picks", "life_safety"],
    phase: "structure",
    lat: 42.9,
    lon: -75.5,
    permitOffice: "Local building department (demo)",
    captain: "D. Russo (PM)",
    blurb: "Dense urban high-rise; union labor and crane sequencing.",
    materialsBudget: 120_000_000,
    startOffsetDays: -320,
  },
  {
    slug: "ma-education-cation",
    name: "Harborview STEM Academy",
    city: "Demo metro (MA)",
    stateCode: "MA",
    industry: "education",
    env: ["cold_winter", "coastal_flood", "urban_dense"],
    interests: ["education_phased", "public_funding", "net_zero", "life_safety"],
    phase: "envelope",
    lat: 42.2,
    lon: -71.5,
    permitOffice: "Local building department (demo)",
    captain: "A. Okafor (GC)",
    blurb: "STEM academy; cold-climate envelope and phased occupancy.",
    materialsBudget: 38_000_000,
    startOffsetDays: -180,
  },
  {
    slug: "pa-multi-family-phimf",
    name: "Navy Yard Workforce Housing",
    city: "Demo metro (PA)",
    stateCode: "PA",
    industry: "multi_family",
    env: ["cold_winter", "urban_dense", "coastal_flood"],
    interests: ["public_funding", "life_safety", "envelope", "modular"],
    phase: "structure",
    lat: 40.9,
    lon: -77.8,
    permitOffice: "Local building department (demo)",
    captain: "T. Nguyen (superintendent)",
    blurb: "Workforce MF; modular pods and winter enclosure.",
    materialsBudget: 27_000_000,
    startOffsetDays: -155,
  },
  {
    slug: "md-civil-lcivil",
    name: "Inner Harbor Storm Outfall",
    city: "Demo metro (MD)",
    stateCode: "MD",
    industry: "civil",
    env: ["coastal_flood", "urban_dense", "wetland_swq", "cold_winter"],
    interests: ["stormwater", "civil_utilities", "public_funding"],
    phase: "structure",
    lat: 39,
    lon: -76.7,
    permitOffice: "Local building department (demo)",
    captain: "R. Blake (civil)",
    blurb: "Storm outfall rehab; MS4 and tide coordination.",
    materialsBudget: 5_100_000,
    startOffsetDays: -110,
  },
  {
    slug: "nj-industrial-strial",
    name: "Portside Cold Storage",
    city: "Demo metro (NJ)",
    stateCode: "NJ",
    industry: "industrial",
    env: ["urban_dense", "coastal_flood", "cold_winter"],
    interests: ["logistics", "steel_structure", "life_safety"],
    phase: "mep",
    lat: 40.1,
    lon: -74.5,
    permitOffice: "Local building department (demo)",
    captain: "P. Kowalski (PM)",
    blurb: "Cold storage industrial; ammonia refrigeration package.",
    materialsBudget: 21_000_000,
    startOffsetDays: -125,
  },
  {
    slug: "ny-renovation-vation",
    name: "Grain Elevator Arts Adaptive Reuse",
    city: "Demo metro (NY)",
    stateCode: "NY",
    industry: "renovation",
    env: ["lake_effect_snow", "cold_winter", "freeze_thaw"],
    interests: ["historic", "envelope", "public_funding"],
    phase: "envelope",
    lat: 42.9,
    lon: -75.5,
    permitOffice: "Local building department (demo)",
    captain: "C. Moretti (GC)",
    blurb: "Adaptive reuse; lake-effect snow load and historic fabric.",
    materialsBudget: 9_800_000,
    startOffsetDays: -200,
  },

  // —— Midwest ——
  {
    slug: "il-multi-family-risemf",
    name: "River North Residences",
    city: "Demo metro (IL)",
    stateCode: "IL",
    industry: "multi_family",
    env: ["cold_winter", "urban_dense", "lake_effect_snow", "freeze_thaw"],
    interests: ["high_rise", "life_safety", "union_labor", "crane_picks"],
    phase: "envelope",
    lat: 40,
    lon: -89.4,
    permitOffice: "Local building department (demo)",
    captain: "M. Kowalski (superintendent)",
    blurb: "High-rise MF; winter enclosure and union sequencing.",
    materialsBudget: 78_000_000,
    startOffsetDays: -290,
  },
  {
    slug: "mi-industrial-strial",
    name: "River Rouge EV Battery Plant Shell",
    city: "Demo metro (MI)",
    stateCode: "MI",
    industry: "industrial",
    env: ["cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["steel_structure", "logistics", "union_labor", "night_work"],
    phase: "structure",
    lat: 44.3,
    lon: -85.4,
    permitOffice: "Local building department (demo)",
    captain: "J. Whitfield (PM)",
    blurb: "Heavy industrial shell; winter steel and process utility stubs.",
    materialsBudget: 140_000_000,
    startOffsetDays: -210,
  },
  {
    slug: "mn-healthcare-thcare",
    name: "Twin Cities Specialty Clinic",
    city: "Demo metro (MN)",
    stateCode: "MN",
    industry: "healthcare",
    env: ["cold_winter", "freeze_thaw"],
    interests: ["healthcare_icra", "life_safety", "envelope"],
    phase: "finish",
    lat: 46.3,
    lon: -94.3,
    permitOffice: "Local building department (demo)",
    captain: "A. Bergstrom (PM)",
    blurb: "Clinic finish; deep-winter moisture control.",
    materialsBudget: 12_400_000,
    startOffsetDays: -230,
  },
  {
    slug: "wi-education-cation",
    name: "Lakefront Technical High School",
    city: "Demo metro (WI)",
    stateCode: "WI",
    industry: "education",
    env: ["cold_winter", "lake_effect_snow", "freeze_thaw"],
    interests: ["education_phased", "public_funding", "life_safety", "net_zero"],
    phase: "mep",
    lat: 44.6,
    lon: -89.8,
    permitOffice: "Local building department (demo)",
    captain: "K. Nowak (GC)",
    blurb: "Tech high school; snow load and energy target.",
    materialsBudget: 52_000_000,
    startOffsetDays: -170,
  },
  {
    slug: "oh-civil-ecivil",
    name: "Cuyahoga Utility Corridor",
    city: "Demo metro (OH)",
    stateCode: "OH",
    industry: "civil",
    env: ["lake_effect_snow", "cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 40.4,
    lon: -82.8,
    permitOffice: "Local building department (demo)",
    captain: "S. Petrović (civil)",
    blurb: "Utility corridor; freeze protection and CSO coordination.",
    materialsBudget: 8_300_000,
    startOffsetDays: -115,
  },
  {
    slug: "mo-renovation-ercial",
    name: "Gateway District Office Renovation",
    city: "Demo metro (MO)",
    stateCode: "MO",
    industry: "renovation",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil", "urban_dense"],
    interests: ["occupied_site", "historic", "life_safety"],
    phase: "mep",
    lat: 38.4,
    lon: -92.5,
    permitOffice: "Local building department (demo)",
    captain: "L. Harper (TI lead)",
    blurb: "Occupied office reno; tornado shelter upgrades.",
    materialsBudget: 6_200_000,
    startOffsetDays: -75,
  },
  {
    slug: "in-single-family-indsfr",
    name: "Broad Ripple Infill SFR",
    city: "Demo metro (IN)",
    stateCode: "IN",
    industry: "single_family",
    env: ["freeze_thaw", "expansive_soil"],
    interests: ["envelope", "stormwater"],
    phase: "precon",
    lat: 39.9,
    lon: -86.3,
    permitOffice: "Local building department (demo)",
    captain: "R. Miles (builder)",
    blurb: "Infill SFR; freeze-depth footings and lot drainage.",
    materialsBudget: 780_000,
    startOffsetDays: -15,
  },
  {
    slug: "mo-multi-family-kcmf",
    name: "Crossroads Lofts MF",
    city: "Demo metro (MO)",
    stateCode: "MO",
    industry: "multi_family",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil"],
    interests: ["life_safety", "steel_structure", "modular"],
    phase: "foundation",
    lat: 38.4,
    lon: -92.5,
    permitOffice: "Local building department (demo)",
    captain: "D. Ortiz (superintendent)",
    blurb: "Urban MF; storm shelter and modular bathroom pods.",
    materialsBudget: 19_500_000,
    startOffsetDays: -55,
  },

  // —— Plains / Mountain north ——
  {
    slug: "ne-industrial-strial",
    name: "Missouri River Ag Processing",
    city: "Demo metro (NE)",
    stateCode: "NE",
    industry: "industrial",
    env: ["freeze_thaw", "tornado_alley", "high_wind_plain"],
    interests: ["steel_structure", "logistics", "life_safety"],
    phase: "structure",
    lat: 41.5,
    lon: -99.8,
    permitOffice: "Local building department (demo)",
    captain: "B. Novak (PM)",
    blurb: "Process industrial; high-wind and freeze protection.",
    materialsBudget: 26_000_000,
    startOffsetDays: -145,
  },
  {
    slug: "nd-civil-ocivil",
    name: "Red River Flood Diversion Segment",
    city: "Demo metro (ND)",
    stateCode: "ND",
    industry: "civil",
    env: ["cold_winter", "freeze_thaw", "wetland_swq"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 47.5,
    lon: -100.5,
    permitOffice: "Local building department (demo)",
    captain: "E. Olson (civil PM)",
    blurb: "Flood diversion civil; deep freeze construction season.",
    materialsBudget: 15_000_000,
    startOffsetDays: -100,
  },
  {
    slug: "mt-hospitality-shotel",
    name: "Yellowstone Gateway Lodge",
    city: "Demo metro (MT)",
    stateCode: "MT",
    industry: "hospitality",
    env: ["cold_winter", "high_altitude", "freeze_thaw", "high_wind_plain"],
    interests: ["hospitality_ffe", "envelope", "life_safety"],
    phase: "envelope",
    lat: 47,
    lon: -109.6,
    permitOffice: "Local building department (demo)",
    captain: "T. Redding (superintendent)",
    blurb: "Cold-climate lodge; wind-driven snow detailing.",
    materialsBudget: 11_200_000,
    startOffsetDays: -165,
  },

  // —— Alaska / Hawaii / unique ——
  {
    slug: "ak-healthcare-thcare",
    name: "Cook Inlet Regional Clinic",
    city: "Demo metro (AK)",
    stateCode: "AK",
    industry: "healthcare",
    env: ["cold_winter", "seismic", "permafrost_edge"],
    interests: ["healthcare_icra", "life_safety", "foundation_deep", "public_funding"],
    phase: "foundation",
    lat: 64.2,
    lon: -149.5,
    permitOffice: "Local building department (demo)",
    captain: "N. Ivanov (PM)",
    blurb: "Clinic on frost-susceptible soils; seismic + thermal piles.",
    materialsBudget: 18_000_000,
    startOffsetDays: -85,
  },
  {
    slug: "hi-hospitality-lhotel",
    name: "Waikiki Courtyard Refresh",
    city: "Demo metro (HI)",
    stateCode: "HI",
    industry: "hospitality",
    env: ["volcanic_island", "coastal_flood", "humid_subtropical", "seismic"],
    interests: ["hospitality_ffe", "envelope", "occupied_site", "life_safety"],
    phase: "finish",
    lat: 20.3,
    lon: -156.4,
    permitOffice: "Local building department (demo)",
    captain: "K. Nakamura (superintendent)",
    blurb: "Occupied hotel refresh; salt air envelope and FF&E.",
    materialsBudget: 14_800_000,
    startOffsetDays: -120,
  },
  {
    slug: "hi-education-cation",
    name: "East Hawaii STEM Annex",
    city: "Demo metro (HI)",
    stateCode: "HI",
    industry: "education",
    env: ["volcanic_island", "humid_subtropical", "seismic", "coastal_flood"],
    interests: ["education_phased", "public_funding", "life_safety", "net_zero"],
    phase: "structure",
    lat: 20.3,
    lon: -156.4,
    permitOffice: "Local building department (demo)",
    captain: "M. Kealoha (GC)",
    blurb: "School annex; volcanic ash and seismic detailing.",
    materialsBudget: 9_600_000,
    startOffsetDays: -95,
  },

  // —— Extra coverage to reach ~50 and more states ——
  {
    slug: "nc-commercial-ercial",
    name: "Capital District Flex Office",
    city: "Demo metro (NC)",
    stateCode: "NC",
    industry: "commercial",
    env: ["humid_subtropical", "expansive_soil"],
    interests: ["steel_structure", "net_zero", "life_safety"],
    phase: "precon",
    lat: 35.6,
    lon: -79.8,
    permitOffice: "Local building department (demo)",
    captain: "H. Park (PM)",
    blurb: "Flex office precon; energy model and steel mill order.",
    materialsBudget: 17_500_000,
    startOffsetDays: -20,
  },
  {
    slug: "fl-industrial-strial",
    name: "Port of Jax Cold Chain",
    city: "Demo metro (FL)",
    stateCode: "FL",
    industry: "industrial",
    env: ["coastal_hurricane", "humid_subtropical", "wetland_swq"],
    interests: ["logistics", "tilt_up", "stormwater"],
    phase: "foundation",
    lat: 28.1,
    lon: -81.7,
    permitOffice: "Local building department (demo)",
    captain: "C. Bennett (PM)",
    blurb: "Port cold chain; wetland buffers and wind design.",
    materialsBudget: 23_000_000,
    startOffsetDays: -60,
  },
  {
    slug: "pa-renovation-vation",
    name: "Steel City Mill Lofts TI",
    city: "Demo metro (PA)",
    stateCode: "PA",
    industry: "renovation",
    env: ["cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["historic", "occupied_site", "envelope"],
    phase: "mep",
    lat: 40.9,
    lon: -77.8,
    permitOffice: "Local building department (demo)",
    captain: "A. Kovacs (TI lead)",
    blurb: "Mill loft TI; freeze pipes and historic steel.",
    materialsBudget: 5_700_000,
    startOffsetDays: -88,
  },
  {
    slug: "oh-single-family-colsfr",
    name: "German Village Carriage House SFR",
    city: "Demo metro (OH)",
    stateCode: "OH",
    industry: "single_family",
    env: ["freeze_thaw", "urban_dense"],
    interests: ["historic", "envelope"],
    phase: "closeout",
    lat: 40.4,
    lon: -82.8,
    permitOffice: "Local building department (demo)",
    captain: "S. Adler (builder)",
    blurb: "Carriage-house SFR closeout; punch and CO path.",
    materialsBudget: 920_000,
    startOffsetDays: -340,
  },
  {
    slug: "tn-civil-mcivil",
    name: "Mississippi Bluff Stabilization",
    city: "Demo metro (TN)",
    stateCode: "TN",
    industry: "civil",
    env: ["humid_subtropical", "wetland_swq", "expansive_soil"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 35.9,
    lon: -86.4,
    permitOffice: "Local building department (demo)",
    captain: "J. Harlan (civil)",
    blurb: "Bluff stabilization; SWQ and access roads.",
    materialsBudget: 4_400_000,
    startOffsetDays: -70,
  },
  {
    slug: "ny-education-cation",
    name: "CTE Center",
    city: "Demo metro (NY)",
    stateCode: "NY",
    industry: "education",
    env: ["cold_winter", "freeze_thaw", "lake_effect_snow"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "structure",
    lat: 42.9,
    lon: -75.5,
    permitOffice: "Local building department (demo)",
    captain: "P. DiMarco (GC)",
    blurb: "CTE center; shop ventilation and winter structure.",
    materialsBudget: 31_000_000,
    startOffsetDays: -135,
  },
  {
    slug: "ok-multi-family-tulmf",
    name: "Live-Work MF",
    city: "Demo metro (OK)",
    stateCode: "OK",
    industry: "multi_family",
    env: ["tornado_alley", "expansive_soil"],
    interests: ["life_safety", "steel_structure", "modular"],
    phase: "mep",
    lat: 35.6,
    lon: -97.5,
    permitOffice: "Local building department (demo)",
    captain: "R. Hale (superintendent)",
    blurb: "Live-work MF; storm shelter and modular wet walls.",
    materialsBudget: 13_800_000,
    startOffsetDays: -105,
  },
  {
    slug: "tx-commercial-ercial",
    name: "Logistics Offices",
    city: "Demo metro (TX)",
    stateCode: "TX",
    industry: "commercial",
    env: ["desert_heat", "high_altitude", "expansive_soil"],
    interests: ["envelope", "logistics", "night_work"],
    phase: "envelope",
    lat: 31.5,
    lon: -99.3,
    permitOffice: "Local building department (demo)",
    captain: "M. Castillo (PM)",
    blurb: "Desert office shell; UV membrane and night roofing.",
    materialsBudget: 8_100_000,
    startOffsetDays: -90,
  },
];

/** Bump when seed shape changes (v8 = 15-min interval field logs). */
export const PROJECT_SEED_VERSION = 9;

export function buildCatalogMeta(): ProjectMeta[] {
  return SEEDS.map((s) => {
    const { slug, ...rest } = s;
    return {
      id: `js_pf_${slug}`,
      ...rest,
      stateCode: rest.stateCode.toUpperCase(),
    };
  });
}

export function catalogStats(meta: ProjectMeta[] = buildCatalogMeta()) {
  const states = new Set(meta.map((m) => m.stateCode));
  const industries = new Set(meta.map((m) => m.industry));
  const envs = new Set(meta.flatMap((m) => m.env));
  return {
    projectCount: meta.length,
    stateCount: states.size,
    stateShareOfUs: states.size / 50,
    industries: [...industries] as ConstructionIndustry[],
    envCount: envs.size,
    states: [...states].sort(),
  };
}
