/**
 * Dynamic local project baseline — ~50 US jobsites across 20+ states,
 * all construction industries, varied environmental conditions.
 * Synthetic field data only; no real municipality PII.
 */

import type { ConstructionIndustry } from "./types";
import type { EnvCondition, InterestTag, ProjectMeta } from "./project-types";

type Seed = Omit<ProjectMeta, "id"> & { slug: string };

const SEEDS: Seed[] = [
  // —— West / Pacific ——
  {
    slug: "sf-mission-sfr",
    name: "Mission Bay Townhome Court",
    city: "San Francisco",
    stateCode: "CA",
    industry: "single_family",
    env: ["seismic", "coastal_flood", "urban_dense"],
    interests: ["envelope", "foundation_deep", "life_safety"],
    phase: "structure",
    lat: 37.7706,
    lon: -122.3892,
    permitOffice: "City building department (demo)",
    captain: "A. Nguyen (superintendent)",
    blurb: "Stacked townhomes on bay fill — seismic + flood plain detailing.",
    materialsBudget: 4_200_000,
    startOffsetDays: -120,
  },
  {
    slug: "la-dtla-mf",
    name: "South Park Residences — Tower A",
    city: "Los Angeles",
    stateCode: "CA",
    industry: "multi_family",
    env: ["seismic", "urban_dense", "wildfire_wui"],
    interests: ["high_rise", "life_safety", "crane_picks", "union_labor"],
    phase: "envelope",
    lat: 34.0407,
    lon: -118.2468,
    permitOffice: "City building department (demo)",
    captain: "R. Alvarez (PM)",
    blurb: "Type I podium MF; curtain wall and life-safety phased floors.",
    materialsBudget: 48_000_000,
    startOffsetDays: -280,
  },
  {
    slug: "sd-biotech-lab",
    name: "Torrey Pines Lab Fit-Out",
    city: "San Diego",
    stateCode: "CA",
    industry: "healthcare",
    env: ["seismic", "coastal_flood"],
    interests: ["healthcare_icra", "occupied_site", "life_safety"],
    phase: "mep",
    lat: 32.899,
    lon: -117.243,
    permitOffice: "City building department (demo)",
    captain: "K. Patel (site lead)",
    blurb: "Occupied lab TI — infection control and specialty gases.",
    materialsBudget: 9_500_000,
    startOffsetDays: -90,
  },
  {
    slug: "sac-school-wing",
    name: "River City Elementary Wing",
    city: "Sacramento",
    stateCode: "CA",
    industry: "education",
    env: ["wildfire_wui", "expansive_soil"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "foundation",
    lat: 38.5816,
    lon: -121.4944,
    permitOffice: "School district / city (demo)",
    captain: "L. Brooks (GC)",
    blurb: "DSA-style phased school wing; summer occupancy target.",
    materialsBudget: 12_000_000,
    startOffsetDays: -45,
  },
  {
    slug: "sea-waterfront-hotel",
    name: "Elliott Bay Boutique Hotel",
    city: "Seattle",
    stateCode: "WA",
    industry: "hospitality",
    env: ["seismic", "coastal_flood", "cold_winter"],
    interests: ["hospitality_ffe", "envelope", "life_safety", "union_labor"],
    phase: "finish",
    lat: 47.6062,
    lon: -122.3321,
    permitOffice: "City building department (demo)",
    captain: "M. Okonkwo (superintendent)",
    blurb: "Waterfront hospitality; FF&E and energy envelope punch.",
    materialsBudget: 22_000_000,
    startOffsetDays: -310,
  },
  {
    slug: "pdx-bridge-civil",
    name: "Willamette Trail Connector",
    city: "Portland",
    stateCode: "OR",
    industry: "civil",
    env: ["wetland_swq", "seismic", "cold_winter"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 45.5152,
    lon: -122.6784,
    permitOffice: "County public works (demo)",
    captain: "J. Hale (civil lead)",
    blurb: "Multi-use path + drainage; wetland SWQ BMPs critical.",
    materialsBudget: 6_800_000,
    startOffsetDays: -160,
  },
  {
    slug: "boise-warehouse",
    name: "Treasure Valley Logistics Hub",
    city: "Boise",
    stateCode: "ID",
    industry: "industrial",
    env: ["freeze_thaw", "high_wind_plain"],
    interests: ["tilt_up", "logistics", "steel_structure"],
    phase: "structure",
    lat: 43.615,
    lon: -116.2023,
    permitOffice: "City building department (demo)",
    captain: "T. Vargas (PM)",
    blurb: "Tilt-up warehouse; freeze protection on slab pours.",
    materialsBudget: 18_500_000,
    startOffsetDays: -100,
  },
  {
    slug: "reno-data-shell",
    name: "Truckee Meadows Data Hall Shell",
    city: "Reno",
    stateCode: "NV",
    industry: "industrial",
    env: ["desert_heat", "seismic", "high_altitude"],
    interests: ["steel_structure", "logistics", "net_zero"],
    phase: "envelope",
    lat: 39.5296,
    lon: -119.8138,
    permitOffice: "City building department (demo)",
    captain: "S. Kim (superintendent)",
    blurb: "Steel shell + heavy power; high desert thermal swings.",
    materialsBudget: 35_000_000,
    startOffsetDays: -200,
  },

  // —— Southwest / Mountain ——
  {
    slug: "phx-retail-pad",
    name: "Desert Ridge Retail Pad B",
    city: "Phoenix",
    stateCode: "AZ",
    industry: "commercial",
    env: ["desert_heat", "expansive_soil"],
    interests: ["envelope", "logistics", "night_work"],
    phase: "mep",
    lat: 33.6846,
    lon: -111.978,
    permitOffice: "City building department (demo)",
    captain: "D. Morales (GC)",
    blurb: "Pad retail under extreme heat — night pours and UV membrane.",
    materialsBudget: 5_400_000,
    startOffsetDays: -70,
  },
  {
    slug: "tucson-mf-garden",
    name: "Catalina Foothills Garden MF",
    city: "Tucson",
    stateCode: "AZ",
    industry: "multi_family",
    env: ["desert_heat", "wildfire_wui"],
    interests: ["life_safety", "stormwater", "envelope"],
    phase: "foundation",
    lat: 32.2535,
    lon: -110.9118,
    permitOffice: "City building department (demo)",
    captain: "P. Ortiz (superintendent)",
    blurb: "Garden-style MF; WUI hardening and monsoon drainage.",
    materialsBudget: 14_200_000,
    startOffsetDays: -40,
  },
  {
    slug: "abq-hospital-wing",
    name: "Rio Grande Med Center Wing C",
    city: "Albuquerque",
    stateCode: "NM",
    industry: "healthcare",
    env: ["high_altitude", "freeze_thaw", "expansive_soil"],
    interests: ["healthcare_icra", "life_safety", "public_funding"],
    phase: "structure",
    lat: 35.0844,
    lon: -106.6504,
    permitOffice: "City building department (demo)",
    captain: "H. Singh (PM)",
    blurb: "Hospital addition; altitude curing and ICRA zones.",
    materialsBudget: 41_000_000,
    startOffsetDays: -190,
  },
  {
    slug: "den-airport-hotel",
    name: "Front Range Airport Hotel",
    city: "Denver",
    stateCode: "CO",
    industry: "hospitality",
    env: ["high_altitude", "freeze_thaw", "high_wind_plain"],
    interests: ["hospitality_ffe", "envelope", "crane_picks"],
    phase: "envelope",
    lat: 39.7392,
    lon: -104.9903,
    permitOffice: "City building department (demo)",
    captain: "C. Berg (superintendent)",
    blurb: "High-altitude hospitality; wind and freeze envelope detailing.",
    materialsBudget: 28_000_000,
    startOffsetDays: -220,
  },
  {
    slug: "slc-office-tower",
    name: "Wasatch Commerce Tower",
    city: "Salt Lake City",
    stateCode: "UT",
    industry: "commercial",
    env: ["seismic", "freeze_thaw", "high_altitude"],
    interests: ["high_rise", "steel_structure", "life_safety"],
    phase: "structure",
    lat: 40.7608,
    lon: -111.891,
    permitOffice: "City building department (demo)",
    captain: "E. Jensen (PM)",
    blurb: "Steel commercial tower; seismic bracing package open.",
    materialsBudget: 62_000_000,
    startOffsetDays: -250,
  },
  {
    slug: "vegas-renovation",
    name: "Strip Corridor TI — Suite 400",
    city: "Las Vegas",
    stateCode: "NV",
    industry: "renovation",
    env: ["desert_heat", "urban_dense"],
    interests: ["occupied_site", "night_work", "hospitality_ffe"],
    phase: "finish",
    lat: 36.1147,
    lon: -115.1728,
    permitOffice: "County building department (demo)",
    captain: "N. Cho (TI lead)",
    blurb: "Occupied casino corridor TI; night work only.",
    materialsBudget: 3_100_000,
    startOffsetDays: -55,
  },

  // —— Texas / South Central ——
  {
    slug: "hou-petrochem-yard",
    name: "Ship Channel Utility Yard",
    city: "Houston",
    stateCode: "TX",
    industry: "civil",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "expansive_soil"],
    interests: ["civil_utilities", "stormwater", "logistics"],
    phase: "structure",
    lat: 29.7604,
    lon: -95.3698,
    permitOffice: "City / county (demo)",
    captain: "B. Carter (civil PM)",
    blurb: "Utility corridor; hurricane and expansive clay staging.",
    materialsBudget: 11_000_000,
    startOffsetDays: -130,
  },
  {
    slug: "dal-mf-midrise",
    name: "Uptown Dallas Mid-Rise MF",
    city: "Dallas",
    stateCode: "TX",
    industry: "multi_family",
    env: ["tornado_alley", "expansive_soil", "humid_subtropical"],
    interests: ["life_safety", "steel_structure", "crane_picks"],
    phase: "mep",
    lat: 32.7767,
    lon: -96.797,
    permitOffice: "City building department (demo)",
    captain: "F. Ramirez (superintendent)",
    blurb: "Mid-rise MF; severe wind and clay foundation monitoring.",
    materialsBudget: 33_000_000,
    startOffsetDays: -175,
  },
  {
    slug: "aus-sfr-green",
    name: "Barton Hills Net-Zero SFR",
    city: "Austin",
    stateCode: "TX",
    industry: "single_family",
    env: ["humid_subtropical", "expansive_soil", "wildfire_wui"],
    interests: ["net_zero", "envelope", "stormwater"],
    phase: "envelope",
    lat: 30.2672,
    lon: -97.7431,
    permitOffice: "City building department (demo)",
    captain: "G. Wells (builder)",
    blurb: "Net-zero SFR; air sealing and rainwater management.",
    materialsBudget: 1_850_000,
    startOffsetDays: -80,
  },
  {
    slug: "sat-industrial",
    name: "Alamo Logistics Crossdock",
    city: "San Antonio",
    stateCode: "TX",
    industry: "industrial",
    env: ["humid_subtropical", "expansive_soil", "high_wind_plain"],
    interests: ["tilt_up", "logistics", "steel_structure"],
    phase: "foundation",
    lat: 29.4241,
    lon: -98.4936,
    permitOffice: "City building department (demo)",
    captain: "I. Soto (PM)",
    blurb: "Tilt-up crossdock; soil prep and dock levelers.",
    materialsBudget: 16_500_000,
    startOffsetDays: -35,
  },
  {
    slug: "okc-school",
    name: "Prairie View Middle School",
    city: "Oklahoma City",
    stateCode: "OK",
    industry: "education",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "structure",
    lat: 35.4676,
    lon: -97.5164,
    permitOffice: "School district (demo)",
    captain: "W. Price (GC)",
    blurb: "Safe-room school; tornado resistance package.",
    materialsBudget: 24_000_000,
    startOffsetDays: -150,
  },
  {
    slug: "nola-hospitality",
    name: "French Quarter Courtyard Inn",
    city: "New Orleans",
    stateCode: "LA",
    industry: "hospitality",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "wetland_swq"],
    interests: ["historic", "hospitality_ffe", "life_safety", "envelope"],
    phase: "finish",
    lat: 29.9511,
    lon: -90.0715,
    permitOffice: "City building department (demo)",
    captain: "Y. Baptiste (superintendent)",
    blurb: "Historic hospitality; floodproofing and FF&E punch.",
    materialsBudget: 8_900_000,
    startOffsetDays: -260,
  },

  // —— Southeast ——
  {
    slug: "mia-highrise-mf",
    name: "Brickell Waterfront Residences",
    city: "Miami",
    stateCode: "FL",
    industry: "multi_family",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical"],
    interests: ["high_rise", "life_safety", "envelope", "crane_picks"],
    phase: "structure",
    lat: 25.7617,
    lon: -80.1918,
    permitOffice: "City building department (demo)",
    captain: "L. Duarte (PM)",
    blurb: "Coastal high-rise MF; impact glazing and surge criteria.",
    materialsBudget: 95_000_000,
    startOffsetDays: -300,
  },
  {
    slug: "tpa-civil-bridge",
    name: "Bay Causeway Utility Rehab",
    city: "Tampa",
    stateCode: "FL",
    industry: "civil",
    env: ["coastal_hurricane", "coastal_flood", "wetland_swq"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "mep",
    lat: 27.9506,
    lon: -82.4572,
    permitOffice: "County public works (demo)",
    captain: "R. Singh (civil)",
    blurb: "Causeway utilities; storm season work windows.",
    materialsBudget: 7_200_000,
    startOffsetDays: -95,
  },
  {
    slug: "atl-commercial",
    name: "Midtown Atlanta Office Shell",
    city: "Atlanta",
    stateCode: "GA",
    industry: "commercial",
    env: ["humid_subtropical", "urban_dense"],
    interests: ["steel_structure", "life_safety", "union_labor"],
    phase: "envelope",
    lat: 33.749,
    lon: -84.388,
    permitOffice: "City building department (demo)",
    captain: "K. Washington (superintendent)",
    blurb: "Urban office shell; fireproofing and curtain wall.",
    materialsBudget: 44_000_000,
    startOffsetDays: -210,
  },
  {
    slug: "chs-sfr-coastal",
    name: "Lowcountry Elevated SFR",
    city: "Charleston",
    stateCode: "SC",
    industry: "single_family",
    env: ["coastal_hurricane", "coastal_flood", "humid_subtropical", "wetland_swq"],
    interests: ["envelope", "stormwater", "foundation_deep"],
    phase: "foundation",
    lat: 32.7765,
    lon: -79.9311,
    permitOffice: "City building department (demo)",
    captain: "A. Rivers (builder)",
    blurb: "Elevated SFR; flood vents and coastal wind straps.",
    materialsBudget: 1_450_000,
    startOffsetDays: -50,
  },
  {
    slug: "clt-healthcare",
    name: "Piedmont Outpatient Pavilion",
    city: "Charlotte",
    stateCode: "NC",
    industry: "healthcare",
    env: ["humid_subtropical", "expansive_soil"],
    interests: ["healthcare_icra", "life_safety", "public_funding"],
    phase: "mep",
    lat: 35.2271,
    lon: -80.8431,
    permitOffice: "City building department (demo)",
    captain: "S. Grant (PM)",
    blurb: "Outpatient pavilion; medical gas and ICRA barriers.",
    materialsBudget: 29_000_000,
    startOffsetDays: -140,
  },
  {
    slug: "nash-hotel",
    name: "Music Row Boutique Hotel",
    city: "Nashville",
    stateCode: "TN",
    industry: "hospitality",
    env: ["humid_subtropical", "tornado_alley"],
    interests: ["hospitality_ffe", "historic", "life_safety"],
    phase: "finish",
    lat: 36.1627,
    lon: -86.7816,
    permitOffice: "City building department (demo)",
    captain: "J. Cole (superintendent)",
    blurb: "Adaptive hospitality; tornado shelter and FF&E.",
    materialsBudget: 15_500_000,
    startOffsetDays: -240,
  },
  {
    slug: "rva-renovation",
    name: "Shockoe Warehouse TI",
    city: "Richmond",
    stateCode: "VA",
    industry: "renovation",
    env: ["humid_subtropical", "urban_dense"],
    interests: ["historic", "occupied_site", "envelope"],
    phase: "mep",
    lat: 37.5407,
    lon: -77.436,
    permitOffice: "City building department (demo)",
    captain: "M. Ellis (TI lead)",
    blurb: "Historic warehouse TI; selective demo and fire egress.",
    materialsBudget: 4_600_000,
    startOffsetDays: -65,
  },

  // —— Mid-Atlantic / Northeast ——
  {
    slug: "nyc-highrise",
    name: "Hudson Yards Block Infill",
    city: "New York",
    stateCode: "NY",
    industry: "commercial",
    env: ["urban_dense", "coastal_flood", "cold_winter"],
    interests: ["high_rise", "steel_structure", "union_labor", "crane_picks", "life_safety"],
    phase: "structure",
    lat: 40.7536,
    lon: -74.0014,
    permitOffice: "City building department (demo)",
    captain: "D. Russo (PM)",
    blurb: "Dense urban high-rise; union labor and crane sequencing.",
    materialsBudget: 120_000_000,
    startOffsetDays: -320,
  },
  {
    slug: "bos-education",
    name: "Harborview STEM Academy",
    city: "Boston",
    stateCode: "MA",
    industry: "education",
    env: ["cold_winter", "coastal_flood", "urban_dense"],
    interests: ["education_phased", "public_funding", "net_zero", "life_safety"],
    phase: "envelope",
    lat: 42.3601,
    lon: -71.0589,
    permitOffice: "City / MSBA-style (demo)",
    captain: "A. Okafor (GC)",
    blurb: "STEM academy; cold-climate envelope and phased occupancy.",
    materialsBudget: 38_000_000,
    startOffsetDays: -180,
  },
  {
    slug: "phi-mf",
    name: "Navy Yard Workforce Housing",
    city: "Philadelphia",
    stateCode: "PA",
    industry: "multi_family",
    env: ["cold_winter", "urban_dense", "coastal_flood"],
    interests: ["public_funding", "life_safety", "envelope", "modular"],
    phase: "structure",
    lat: 39.9526,
    lon: -75.1652,
    permitOffice: "City building department (demo)",
    captain: "T. Nguyen (superintendent)",
    blurb: "Workforce MF; modular pods and winter enclosure.",
    materialsBudget: 27_000_000,
    startOffsetDays: -155,
  },
  {
    slug: "bal-civil",
    name: "Inner Harbor Storm Outfall",
    city: "Baltimore",
    stateCode: "MD",
    industry: "civil",
    env: ["coastal_flood", "urban_dense", "wetland_swq", "cold_winter"],
    interests: ["stormwater", "civil_utilities", "public_funding"],
    phase: "structure",
    lat: 39.2904,
    lon: -76.6122,
    permitOffice: "City public works (demo)",
    captain: "R. Blake (civil)",
    blurb: "Storm outfall rehab; MS4 and tide coordination.",
    materialsBudget: 5_100_000,
    startOffsetDays: -110,
  },
  {
    slug: "nwk-industrial",
    name: "Portside Cold Storage",
    city: "Newark",
    stateCode: "NJ",
    industry: "industrial",
    env: ["urban_dense", "coastal_flood", "cold_winter"],
    interests: ["logistics", "steel_structure", "life_safety"],
    phase: "mep",
    lat: 40.7357,
    lon: -74.1724,
    permitOffice: "City building department (demo)",
    captain: "P. Kowalski (PM)",
    blurb: "Cold storage industrial; ammonia refrigeration package.",
    materialsBudget: 21_000_000,
    startOffsetDays: -125,
  },
  {
    slug: "buf-renovation",
    name: "Grain Elevator Arts Adaptive Reuse",
    city: "Buffalo",
    stateCode: "NY",
    industry: "renovation",
    env: ["lake_effect_snow", "cold_winter", "freeze_thaw"],
    interests: ["historic", "envelope", "public_funding"],
    phase: "envelope",
    lat: 42.8864,
    lon: -78.8784,
    permitOffice: "City building department (demo)",
    captain: "C. Moretti (GC)",
    blurb: "Adaptive reuse; lake-effect snow load and historic fabric.",
    materialsBudget: 9_800_000,
    startOffsetDays: -200,
  },

  // —— Midwest ——
  {
    slug: "chi-highrise-mf",
    name: "River North Residences",
    city: "Chicago",
    stateCode: "IL",
    industry: "multi_family",
    env: ["cold_winter", "urban_dense", "lake_effect_snow", "freeze_thaw"],
    interests: ["high_rise", "life_safety", "union_labor", "crane_picks"],
    phase: "envelope",
    lat: 41.8781,
    lon: -87.6298,
    permitOffice: "City building department (demo)",
    captain: "M. Kowalski (superintendent)",
    blurb: "High-rise MF; winter enclosure and union sequencing.",
    materialsBudget: 78_000_000,
    startOffsetDays: -290,
  },
  {
    slug: "det-industrial",
    name: "River Rouge EV Battery Plant Shell",
    city: "Detroit",
    stateCode: "MI",
    industry: "industrial",
    env: ["cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["steel_structure", "logistics", "union_labor", "night_work"],
    phase: "structure",
    lat: 42.3314,
    lon: -83.0458,
    permitOffice: "City building department (demo)",
    captain: "J. Whitfield (PM)",
    blurb: "Heavy industrial shell; winter steel and process utility stubs.",
    materialsBudget: 140_000_000,
    startOffsetDays: -210,
  },
  {
    slug: "msp-healthcare",
    name: "Twin Cities Specialty Clinic",
    city: "Minneapolis",
    stateCode: "MN",
    industry: "healthcare",
    env: ["cold_winter", "freeze_thaw"],
    interests: ["healthcare_icra", "life_safety", "envelope"],
    phase: "finish",
    lat: 44.9778,
    lon: -93.265,
    permitOffice: "City building department (demo)",
    captain: "A. Bergstrom (PM)",
    blurb: "Clinic finish; deep-winter moisture control.",
    materialsBudget: 12_400_000,
    startOffsetDays: -230,
  },
  {
    slug: "mil-education",
    name: "Lakefront Technical High School",
    city: "Milwaukee",
    stateCode: "WI",
    industry: "education",
    env: ["cold_winter", "lake_effect_snow", "freeze_thaw"],
    interests: ["education_phased", "public_funding", "life_safety", "net_zero"],
    phase: "mep",
    lat: 43.0389,
    lon: -87.9065,
    permitOffice: "School district (demo)",
    captain: "K. Nowak (GC)",
    blurb: "Tech high school; snow load and energy target.",
    materialsBudget: 52_000_000,
    startOffsetDays: -170,
  },
  {
    slug: "cle-civil",
    name: "Cuyahoga Utility Corridor",
    city: "Cleveland",
    stateCode: "OH",
    industry: "civil",
    env: ["lake_effect_snow", "cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 41.4993,
    lon: -81.6944,
    permitOffice: "City public works (demo)",
    captain: "S. Petrović (civil)",
    blurb: "Utility corridor; freeze protection and CSO coordination.",
    materialsBudget: 8_300_000,
    startOffsetDays: -115,
  },
  {
    slug: "stl-commercial",
    name: "Gateway District Office Renovation",
    city: "St. Louis",
    stateCode: "MO",
    industry: "renovation",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil", "urban_dense"],
    interests: ["occupied_site", "historic", "life_safety"],
    phase: "mep",
    lat: 38.627,
    lon: -90.1994,
    permitOffice: "City building department (demo)",
    captain: "L. Harper (TI lead)",
    blurb: "Occupied office reno; tornado shelter upgrades.",
    materialsBudget: 6_200_000,
    startOffsetDays: -75,
  },
  {
    slug: "ind-sfr",
    name: "Broad Ripple Infill SFR",
    city: "Indianapolis",
    stateCode: "IN",
    industry: "single_family",
    env: ["freeze_thaw", "expansive_soil"],
    interests: ["envelope", "stormwater"],
    phase: "precon",
    lat: 39.7684,
    lon: -86.1581,
    permitOffice: "City building department (demo)",
    captain: "R. Miles (builder)",
    blurb: "Infill SFR; freeze-depth footings and lot drainage.",
    materialsBudget: 780_000,
    startOffsetDays: -15,
  },
  {
    slug: "kc-mf",
    name: "Crossroads Lofts MF",
    city: "Kansas City",
    stateCode: "MO",
    industry: "multi_family",
    env: ["tornado_alley", "freeze_thaw", "expansive_soil"],
    interests: ["life_safety", "steel_structure", "modular"],
    phase: "foundation",
    lat: 39.0997,
    lon: -94.5786,
    permitOffice: "City building department (demo)",
    captain: "D. Ortiz (superintendent)",
    blurb: "Urban MF; storm shelter and modular bathroom pods.",
    materialsBudget: 19_500_000,
    startOffsetDays: -55,
  },

  // —— Plains / Mountain north ——
  {
    slug: "oma-industrial",
    name: "Missouri River Ag Processing",
    city: "Omaha",
    stateCode: "NE",
    industry: "industrial",
    env: ["freeze_thaw", "tornado_alley", "high_wind_plain"],
    interests: ["steel_structure", "logistics", "life_safety"],
    phase: "structure",
    lat: 41.2565,
    lon: -95.9345,
    permitOffice: "City building department (demo)",
    captain: "B. Novak (PM)",
    blurb: "Process industrial; high-wind and freeze protection.",
    materialsBudget: 26_000_000,
    startOffsetDays: -145,
  },
  {
    slug: "fargo-civil",
    name: "Red River Flood Diversion Segment",
    city: "Fargo",
    stateCode: "ND",
    industry: "civil",
    env: ["cold_winter", "freeze_thaw", "wetland_swq"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 46.8772,
    lon: -96.7898,
    permitOffice: "County / state (demo)",
    captain: "E. Olson (civil PM)",
    blurb: "Flood diversion civil; deep freeze construction season.",
    materialsBudget: 15_000_000,
    startOffsetDays: -100,
  },
  {
    slug: "billings-hotel",
    name: "Yellowstone Gateway Lodge",
    city: "Billings",
    stateCode: "MT",
    industry: "hospitality",
    env: ["cold_winter", "high_altitude", "freeze_thaw", "high_wind_plain"],
    interests: ["hospitality_ffe", "envelope", "life_safety"],
    phase: "envelope",
    lat: 45.7833,
    lon: -108.5007,
    permitOffice: "City building department (demo)",
    captain: "T. Redding (superintendent)",
    blurb: "Cold-climate lodge; wind-driven snow detailing.",
    materialsBudget: 11_200_000,
    startOffsetDays: -165,
  },

  // —— Alaska / Hawaii / unique ——
  {
    slug: "anc-healthcare",
    name: "Cook Inlet Regional Clinic",
    city: "Anchorage",
    stateCode: "AK",
    industry: "healthcare",
    env: ["cold_winter", "seismic", "permafrost_edge"],
    interests: ["healthcare_icra", "life_safety", "foundation_deep", "public_funding"],
    phase: "foundation",
    lat: 61.2181,
    lon: -149.9003,
    permitOffice: "Municipality (demo)",
    captain: "N. Ivanov (PM)",
    blurb: "Clinic on frost-susceptible soils; seismic + thermal piles.",
    materialsBudget: 18_000_000,
    startOffsetDays: -85,
  },
  {
    slug: "hnl-hotel",
    name: "Waikiki Courtyard Refresh",
    city: "Honolulu",
    stateCode: "HI",
    industry: "hospitality",
    env: ["volcanic_island", "coastal_flood", "humid_subtropical", "seismic"],
    interests: ["hospitality_ffe", "envelope", "occupied_site", "life_safety"],
    phase: "finish",
    lat: 21.3069,
    lon: -157.8583,
    permitOffice: "City & County (demo)",
    captain: "K. Nakamura (superintendent)",
    blurb: "Occupied hotel refresh; salt air envelope and FF&E.",
    materialsBudget: 14_800_000,
    startOffsetDays: -120,
  },
  {
    slug: "hilo-education",
    name: "East Hawaii STEM Annex",
    city: "Hilo",
    stateCode: "HI",
    industry: "education",
    env: ["volcanic_island", "humid_subtropical", "seismic", "coastal_flood"],
    interests: ["education_phased", "public_funding", "life_safety", "net_zero"],
    phase: "structure",
    lat: 19.7074,
    lon: -155.0885,
    permitOffice: "State / county (demo)",
    captain: "M. Kealoha (GC)",
    blurb: "School annex; volcanic ash and seismic detailing.",
    materialsBudget: 9_600_000,
    startOffsetDays: -95,
  },

  // —— Extra coverage to reach ~50 and more states ——
  {
    slug: "ric-commercial",
    name: "Capital District Flex Office",
    city: "Raleigh",
    stateCode: "NC",
    industry: "commercial",
    env: ["humid_subtropical", "expansive_soil"],
    interests: ["steel_structure", "net_zero", "life_safety"],
    phase: "precon",
    lat: 35.7796,
    lon: -78.6382,
    permitOffice: "City building department (demo)",
    captain: "H. Park (PM)",
    blurb: "Flex office precon; energy model and steel mill order.",
    materialsBudget: 17_500_000,
    startOffsetDays: -20,
  },
  {
    slug: "jax-industrial",
    name: "Port of Jax Cold Chain",
    city: "Jacksonville",
    stateCode: "FL",
    industry: "industrial",
    env: ["coastal_hurricane", "humid_subtropical", "wetland_swq"],
    interests: ["logistics", "tilt_up", "stormwater"],
    phase: "foundation",
    lat: 30.3322,
    lon: -81.6557,
    permitOffice: "City building department (demo)",
    captain: "C. Bennett (PM)",
    blurb: "Port cold chain; wetland buffers and wind design.",
    materialsBudget: 23_000_000,
    startOffsetDays: -60,
  },
  {
    slug: "pit-renovation",
    name: "Steel City Mill Lofts TI",
    city: "Pittsburgh",
    stateCode: "PA",
    industry: "renovation",
    env: ["cold_winter", "freeze_thaw", "urban_dense"],
    interests: ["historic", "occupied_site", "envelope"],
    phase: "mep",
    lat: 40.4406,
    lon: -79.9959,
    permitOffice: "City building department (demo)",
    captain: "A. Kovacs (TI lead)",
    blurb: "Mill loft TI; freeze pipes and historic steel.",
    materialsBudget: 5_700_000,
    startOffsetDays: -88,
  },
  {
    slug: "col-sfr",
    name: "German Village Carriage House SFR",
    city: "Columbus",
    stateCode: "OH",
    industry: "single_family",
    env: ["freeze_thaw", "urban_dense"],
    interests: ["historic", "envelope"],
    phase: "closeout",
    lat: 39.9612,
    lon: -82.9988,
    permitOffice: "City building department (demo)",
    captain: "S. Adler (builder)",
    blurb: "Carriage-house SFR closeout; punch and CO path.",
    materialsBudget: 920_000,
    startOffsetDays: -340,
  },
  {
    slug: "mem-civil",
    name: "Mississippi Bluff Stabilization",
    city: "Memphis",
    stateCode: "TN",
    industry: "civil",
    env: ["humid_subtropical", "wetland_swq", "expansive_soil"],
    interests: ["civil_utilities", "stormwater", "public_funding"],
    phase: "structure",
    lat: 35.1495,
    lon: -90.049,
    permitOffice: "City public works (demo)",
    captain: "J. Harlan (civil)",
    blurb: "Bluff stabilization; SWQ and access roads.",
    materialsBudget: 4_400_000,
    startOffsetDays: -70,
  },
  {
    slug: "alb-education",
    name: "Capital Region CTE Center",
    city: "Albany",
    stateCode: "NY",
    industry: "education",
    env: ["cold_winter", "freeze_thaw", "lake_effect_snow"],
    interests: ["education_phased", "public_funding", "life_safety"],
    phase: "structure",
    lat: 42.6526,
    lon: -73.7562,
    permitOffice: "School district (demo)",
    captain: "P. DiMarco (GC)",
    blurb: "CTE center; shop ventilation and winter structure.",
    materialsBudget: 31_000_000,
    startOffsetDays: -135,
  },
  {
    slug: "tul-mf",
    name: "Arts District Live-Work MF",
    city: "Tulsa",
    stateCode: "OK",
    industry: "multi_family",
    env: ["tornado_alley", "expansive_soil"],
    interests: ["life_safety", "steel_structure", "modular"],
    phase: "mep",
    lat: 36.154,
    lon: -95.9928,
    permitOffice: "City building department (demo)",
    captain: "R. Hale (superintendent)",
    blurb: "Live-work MF; storm shelter and modular wet walls.",
    materialsBudget: 13_800_000,
    startOffsetDays: -105,
  },
  {
    slug: "elp-commercial",
    name: "Borderland Logistics Offices",
    city: "El Paso",
    stateCode: "TX",
    industry: "commercial",
    env: ["desert_heat", "high_altitude", "expansive_soil"],
    interests: ["envelope", "logistics", "night_work"],
    phase: "envelope",
    lat: 31.7619,
    lon: -106.485,
    permitOffice: "City building department (demo)",
    captain: "M. Castillo (PM)",
    blurb: "Desert office shell; UV membrane and night roofing.",
    materialsBudget: 8_100_000,
    startOffsetDays: -90,
  },
];

/** Bump when seed shape changes (v8 = 15-min interval field logs). */
export const PROJECT_SEED_VERSION = 8;

export function buildCatalogMeta(): ProjectMeta[] {
  return SEEDS.map((s) => {
    const { slug, ...rest } = s;
    return {
      id: `js_pf_${slug}`,
      ...rest,
      stateCode: rest.stateCode.toUpperCase(),
    };
  });
}

export function catalogStats(meta: ProjectMeta[] = buildCatalogMeta()) {
  const states = new Set(meta.map((m) => m.stateCode));
  const industries = new Set(meta.map((m) => m.industry));
  const envs = new Set(meta.flatMap((m) => m.env));
  return {
    projectCount: meta.length,
    stateCount: states.size,
    stateShareOfUs: states.size / 50,
    industries: [...industries] as ConstructionIndustry[],
    envCount: envs.size,
    states: [...states].sort(),
  };
}
