/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as JobsiteRouteImport } from './routes/jobsite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsiteRoute = JobsiteRouteImport.update({
  id: '/jobsite',
  path: '/jobsite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/jobsite': typeof JobsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/jobsite': typeof JobsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/jobsite': typeof JobsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/claims' | '/jobsite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claims' | '/jobsite'
  id: '__root__' | '/' | '/claims' | '/jobsite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsRoute: typeof ClaimsRoute
  JobsiteRoute: typeof JobsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobsite': {
      id: '/jobsite'
      path: '/jobsite'
      fullPath: '/jobsite'
      preLoaderRoute: typeof JobsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsRoute: ClaimsRoute,
  JobsiteRoute: JobsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
